version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://notes:notes@db:5432/notes
      SECRET_KEY: local_dev_secret
      CORS_ORIGINS: "*"
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
