
name: Trivy
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t notes-api .
      - name: Scan image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'notes-api:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
